export const apiData = {
  lessons: [
    {
      title: "Seja Bem-vindo(a)",
      duration: "0:08:13",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Plataforma de Aulas",
      duration: "0:07:04",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "A Comunidade",
      duration: "0:15:38",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Juntos vamos mais rápido e mais longe",
      duration: "0:09:14",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Encontre seu Partner",
      duration: "0:04:08",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Aprendendo a Aprender pt. 1",
      duration: "0:08:54",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Aprendendo a Aprender pt. 2",
      duration: "0:09:52",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Você merece um troféu",
      duration: "0:05:25",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "O segredo para o Sucesso",
      duration: "0:05:05",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Como atingir o Sucesso",
      duration: "0:10:20",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Não cometa esses Erros",
      duration: "0:12:25",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Quadro de Metas",
      duration: "0:12:20",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Cronograma de Estudos",
      duration: "0:05:30",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Conclusão",
      duration: "0:03:30",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "App DevClub",
      duration: "0:02:46",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Comunidade DevClub",
      duration: "0:15:37",
      finished: false,
      module: "2",
      summary: "",
    },
    {
      title: "Materiais complementares",
      duration: "0:00:30",
      finished: false,
      module: "3",
      summary: "",
    },
    {
      title: "Introdução",
      duration: "0:04:06",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "Instalando o VsCode",
      duration: "0:07:12",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "VsCode em Português",
      duration: "0:02:32",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "Extensões VsCode",
      duration: "0:07:18",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "Instalando o Node",
      duration: "0:03:50",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "Conclusão",
      duration: "0:00:47",
      finished: false,
      module: "4",
      summary: "",
    },
    {
      title: "Introdução",
      duration: "0:12:10",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Criando primeiro arquivo HTML",
      duration: "0:04:56",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "TAG'S HTML",
      duration: "0:14:34",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Estrutura de uma página HTML",
      duration: "0:06:55",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "SEO",
      duration: "0:04:19",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "TAG'S para texto",
      duration: "0:08:59",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Navegando entre pastas",
      duration: "0:13:17",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Links",
      duration: "0:11:38",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Listas",
      duration: "0:04:36",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Elementos estruturais",
      duration: "0:12:05",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Imagens no HTML",
      duration: "0:08:23",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Desafio",
      duration: "0:05:01",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Desafio resolvido",
      duration: "0:07:58",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Tabelas",
      duration: "0:05:06",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Vídeos",
      duration: "0:09:18",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "iFrame",
      duration: "0:05:27",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Input pt. 1",
      duration: "0:08:54",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Input pt. 2",
      duration: "0:03:28",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Input pt. 3",
      duration: "0:10:51",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Forms",
      duration: "0:18:01",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Button",
      duration: "0:02:57",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Clean Code",
      duration: "0:05:02",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "HTML Semântico",
      duration: "0:07:26",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Conclusão do Módulo",
      duration: "0:01:18",
      finished: false,
      module: "5",
      summary: "",
    },
    {
      title: "Introdução",
      duration: "0:04:33",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Iniciando no CSS",
      duration: "0:10:30",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "CSS no HTML",
      duration: "0:05:54",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Seletores CSS",
      duration: "0:12:56",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Folha de estilo em CASCATA",
      duration: "0:03:11",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Cores no CSS",
      duration: "0:11:44",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Unidade de medidas CSS",
      duration: "0:20:31",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Textos",
      duration: "0:16:34",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Padding e Margin",
      duration: "0:16:51",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Box-sizing",
      duration: "0:08:01",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Display",
      duration: "0:09:39",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Programador não é Designer",
      duration: "0:07:53",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Projeto pt. 1 - HTML",
      duration: "0:08:39",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Projeto pt. 2 - CSS",
      duration: "0:16:40",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Projeto pt. 3 - CSS",
      duration: "0:11:56",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Desafio 1",
      duration: "0:02:52",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "Desafio 1 - Resolvido",
      duration: "0:20:15",
      finished: false,
      module: "6",
      summary: "",
    },
    {
      title: "!important",
      duration: "0:03:11",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Position pt. 1",
      duration: "0:12:27",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Position pt. 2",
      duration: "0:10:45",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Pseudo elementos",
      duration: "0:07:12",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Pseudo classes pt. 1",
      duration: "0:15:43",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Pseudo classes pt. 2",
      duration: "0:10:23",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Responsividade pt. 1",
      duration: "0:08:25",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Responsividade pt. 2",
      duration: "0:06:58",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Projeto pt. 1",
      duration: "0:09:58",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Projeto pt. 2",
      duration: "0:14:52",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Projeto pt. 3",
      duration: "0:16:07",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Projeto pt. 4",
      duration: "0:17:24",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Desafio",
      duration: "0:01:23",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Calc",
      duration: "0:05:04",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Conclusão",
      duration: "0:00:58",
      finished: false,
      module: "7",
      summary: "",
    },
    {
      title: "Intro - O que é Git & Github",
      duration: "0:09:51",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Instalando o GIT",
      duration: "0:08:28",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Entendendo o Github",
      duration: "0:05:07",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Criando conta no Github",
      duration: "0:03:54",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Logando no Github localmente",
      duration: "0:15:38",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Criando primeiro repositório",
      duration: "0:06:00",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Adicionando arquivos na área de Stage",
      duration: "0:12:29",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Fazendo o primeiro Commit",
      duration: "0:05:50",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Instalando novas extensões no VsCode",
      duration: "0:08:29",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Git push",
      duration: "0:10:12",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Git pull",
      duration: "0:04:51",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Git com linha de comando",
      duration: "0:06:43",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Subindo projeto do ZERO",
      duration: "0:14:08",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Resumo",
      duration: "0:05:36",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Desafio",
      duration: "0:01:38",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Entendendo o conceito de Branches",
      duration: "0:07:55",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Branches na prática",
      duration: "0:14:15",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Git merge",
      duration: "0:09:02",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Editando o perfil do Github",
      duration: "0:20:04",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Criando um README.md dos projetos",
      duration: "0:14:36",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Publicando seus projetos",
      duration: "0:04:02",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Desafio final Git & Github",
      duration: "0:02:26",
      finished: false,
      module: "8",
      summary: "",
    },
    {
      title: "Introdução ao Módulo",
      duration: "0:06:10",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Por que aprender JavaScript ?",
      duration: "0:12:29",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Lógica de Programação e Algoritmo NA PRÁTICA",
      duration: "0:19:02",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Como executar JavaScript ?",
      duration: "0:11:10",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Dica para você Evoluir",
      duration: "0:03:54",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "O que são Variáveis",
      duration: "0:14:10",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Strings",
      duration: "0:05:42",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Template Strings",
      duration: "0:04:44",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Numbers",
      duration: "0:03:19",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Boolean",
      duration: "0:04:26",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Object",
      duration: "0:15:43",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Null & Undefined",
      duration: "0:04:49",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Array",
      duration: "0:11:32",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "if & else",
      duration: "0:15:10",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "Functions",
      duration: "0:08:35",
      finished: false,
      module: "9",
      summary: "",
    },
    {
      title: "JavaScript e a DOM",
      duration: "0:07:23",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Conectando JavaScript nos nossos sites",
      duration: "0:06:22",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Entendendo próximos passos",
      duration: "0:03:10",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "getElementById",
      duration: "0:03:28",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "getElementByClassName",
      duration: "0:03:20",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "getElementByTagName",
      duration: "0:01:27",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "getElementByName",
      duration: "0:02:42",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "querySelector",
      duration: "0:04:15",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "querySelectorAll",
      duration: "0:01:42",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Alterando elementos na prática",
      duration: "0:03:48",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Alterando textos & HTML no JavaScript",
      duration: "0:10:19",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Alterando CSS(estilos) no JavaScript",
      duration: "0:03:41",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Eventos",
      duration: "0:17:54",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "AddEventListener",
      duration: "0:16:21",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Vamos para o Projeto Prático",
      duration: "0:02:57",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "HTML da nossa aplicação",
      duration: "0:13:20",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "CSS da nossa aplicação",
      duration: "0:24:45",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Como fazer a lógica de qualquer aplicação",
      duration: "0:05:58",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "JavaScript pt.1",
      duration: "0:11:44",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "JavaScript pt.2",
      duration: "0:14:29",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "JavaScript pt.3",
      duration: "0:11:33",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "JavaScript pt.4",
      duration: "0:12:49",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Desafio",
      duration: "0:05:13",
      finished: false,
      module: "10",
      summary: "",
    },
    {
      title: "Math",
      duration: "0:08:01",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Projeto Random",
      duration: "0:18:27",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores Aritméticos",
      duration: "0:11:30",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores de Atribuição",
      duration: "0:07:15",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores de comparação",
      duration: "0:11:14",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores de comparação pt.2",
      duration: "0:10:21",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores lógicos",
      duration: "0:15:07",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operadores type of e delete",
      duration: "0:02:18",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Else if",
      duration: "0:05:56",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Operador ternário",
      duration: "0:12:22",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "Switch case",
      duration: "0:08:41",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "SetTimeout & setInterval",
      duration: "0:17:00",
      finished: false,
      module: "11",
      summary: "",
    },
    {
      title: "For",
      duration: "0:12:56",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Desafio for",
      duration: "0:15:14",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "For of",
      duration: "0:08:20",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "For in",
      duration: "0:06:29",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Do while",
      duration: "0:06:28",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Foreach",
      duration: "0:15:13",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Function Argumentos/Parâmetros",
      duration: "0:17:00",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Function Return",
      duration: "0:14:07",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Desafio Resolvido",
      duration: "0:17:25",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Arrow Functions",
      duration: "0:07:15",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Function Anônima",
      duration: "0:01:09",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Projeto Functions pt.1",
      duration: "0:03:56",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Projeto Functions pt.2",
      duration: "0:16:14",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Projeto Functions pt.3",
      duration: "0:25:28",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "ENUM",
      duration: "0:07:45",
      finished: false,
      module: "12",
      summary: "",
    },
    {
      title: "Map",
      duration: "0:10:02",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Map pt.2",
      duration: "0:13:23",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Reduce",
      duration: "0:17:42",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Filter",
      duration: "0:12:27",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Map, Reduce & Filter",
      duration: "0:17:52",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Métodos de Array",
      duration: "0:29:57",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto Apresentação",
      duration: "0:02:02",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - HTML",
      duration: "0:03:44",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - CSS",
      duration: "0:15:47",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - Desafio",
      duration: "0:05:52",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - For Each",
      duration: "0:13:22",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - MAP",
      duration: "0:23:00",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - REDUCE",
      duration: "0:09:17",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Projeto - FILTER",
      duration: "0:09:33",
      finished: false,
      module: "13",
      summary: "",
    },
    {
      title: "Introdução",
      duration: "0:05:07",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Vença seus inimigos",
      duration: "0:15:21",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Mindset DevClub",
      duration: "0:16:15",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Como funciona os processos seletivos na Programação",
      duration: "0:10:19",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Parabéns, você está contratado(a)",
      duration: "0:07:16",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Onde conseguir Emprego?",
      duration: "0:06:47",
      finished: false,
      module: "14",
      summary: "",
    },
    {
      title: "Linkedin pt.1",
      duration: "0:13:26",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Linkedin pt.2",
      duration: "0:13:24",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Linkedin pt.3",
      duration: "0:11:54",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Linkedin pt.4",
      duration: "0:10:27",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Linkedin pt.5",
      duration: "0:10:35",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Linkedin pt.6",
      duration: "0:10:23",
      finished: false,
      module: "15",
      summary: "",
    },
    {
      title: "Faça um currículo perfeito",
      duration: "0:08:17",
      finished: false,
      module: "16",
      summary: "",
    },
    {
      title: "Faça um currículo perfeito pt.2",
      duration: "0:14:54",
      finished: false,
      module: "16",
      summary: "",
    },
    {
      title: "Entrevista pt. 1",
      duration: "0:28:24",
      finished: false,
      module: "17",
      summary: "",
    },
    {
      title: "Entrevista pt. 2",
      duration: "0:18:59",
      finished: false,
      module: "17",
      summary: "",
    },
    {
      title: "Entrevista pt. 3",
      duration: "0:18:12",
      finished: false,
      module: "17",
      summary: "",
    },
    {
      title: "Entrevista pt. 4",
      duration: "0:06:51",
      finished: false,
      module: "17",
      summary: "",
    },
    {
      title: "Missão Primeiro Emprego",
      duration: "0:08:29",
      finished: false,
      module: "18",
      summary: "",
    },
    {
      title: "Conclusão",
      duration: "0:02:45",
      finished: false,
      module: "18",
      summary: "",
    },
    {
      title: "Como ganhar dinheiro com Freela",
      duration: "0:09:23",
      finished: false,
      module: "19",
      summary: "",
    },
    {
      title: "Introdução",
      duration: "0:00:34",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Conceito de Back end e Front end",
      duration: "0:16:08",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Conceito de Node",
      duration: "0:23:50",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Protocolo HTTP",
      duration: "0:20:49",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Instalando o Node",
      duration: "0:01:16",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "NPM - Gerenciador de pacotes do Node",
      duration: "0:01:26",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Iniciando um projeto Node",
      duration: "0:06:52",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "VsCode - Instalando o Command Path",
      duration: "0:02:09",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Instalando o Express",
      duration: "0:10:48",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Express",
      duration: "0:11:29",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Instalando o Insomnia",
      duration: "0:04:21",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Instalando o Nodemon",
      duration: "0:06:03",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "JSON",
      duration: "0:02:27",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Query Params",
      duration: "0:12:08",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Route Params",
      duration: "0:04:52",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Body Params",
      duration: "0:04:06",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Primeiro projeto Node pt. 1",
      duration: "0:11:08",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Primeiro projeto Node pt. 2",
      duration: "0:15:10",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Primeiro projeto Node pt. 3",
      duration: "0:05:31",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Middlewares",
      duration: "0:19:58",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Debugando nossa aplicação",
      duration: "0:05:12",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Gitignore",
      duration: "0:04:33",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "Desafio Node",
      duration: "0:05:59",
      finished: false,
      module: "20",
      summary: "",
    },
    {
      title: "API, API REST E API RESTFUL",
      duration: "0:14:32",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Var x Let x Const",
      duration: "0:10:49",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Módulos no Node",
      duration: "0:11:25",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Entendendo o this",
      duration: "0:15:10",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Lidando com erros - Try & Catch",
      duration: "0:11:33",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Promises e Async Await",
      duration: "0:19:22",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Classes",
      duration: "0:14:01",
      finished: false,
      module: "21",
      summary: "",
    },
    {
      title: "Display flex",
      duration: "0:04:03",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Direction",
      duration: "0:02:29",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Wrap",
      duration: "0:02:21",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Flow",
      duration: "0:01:52",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Justify Content",
      duration: "0:03:38",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Align Items",
      duration: "0:02:33",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Align Content",
      duration: "0:03:19",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Gap",
      duration: "0:00:46",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Basis",
      duration: "0:01:57",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Grow",
      duration: "0:03:10",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex Shrink",
      duration: "0:02:19",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Flex",
      duration: "0:02:21",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Order",
      duration: "0:01:56",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Align Self",
      duration: "0:02:00",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Origamid",
      duration: "0:02:23",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Convert Money com Display Flex",
      duration: "0:08:33",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Desafio Flex Box",
      duration: "0:03:06",
      finished: false,
      module: "22",
      summary: "",
    },
    {
      title: "Introdução ao React",
      duration: "0:15:19",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Instalando o Yarn",
      duration: "0:04:00",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Iniciando um projeto React",
      duration: "0:13:10",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Entendendo a sintaxe JSX",
      duration: "0:04:00",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "CSS no React",
      duration: "0:02:11",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Styled Components",
      duration: "0:07:43",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Estrutura HTML do projeto",
      duration: "0:04:55",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Imagens no React",
      duration: "0:07:31",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Estilos globais no React",
      duration: "0:06:56",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Estilizando a aplicação",
      duration: "0:15:36",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Finalizando a estilização",
      duration: "0:02:34",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Renderizando vários itens no React",
      duration: "0:09:20",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Estilizando Card de usuário",
      duration: "0:06:37",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Entendendo o conceito de Estado no React",
      duration: "0:12:24",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Pegando valores do Inputs",
      duration: "0:06:31",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Spread operator",
      duration: "0:07:05",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Aprendendo React Hook - Use Ref",
      duration: "0:07:26",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Deletando usuários",
      duration: "0:07:06",
      finished: false,
      module: "23",
      summary: "",
    },
    {
      title: "Conectando Front-end e Back-end",
      duration: "0:14:38",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Cadastrando novos usuários no Back-end",
      duration: "0:04:41",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Recuperando usuários no Back-end",
      duration: "0:04:02",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Aprendendo sobre o React Hook - UseEffect",
      duration: "0:10:55",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Deletando um usuário",
      duration: "0:02:54",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Iniciando criação da tela de listagem de usuários",
      duration: "0:07:12",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Estilizando tela de listagem de usuários",
      duration: "0:08:43",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "ATUALIZAÇÃO - React Router Dom v6",
      duration: "0:00:20",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Criando as rotas da nossa aplicação",
      duration: "0:13:05",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Navegando entre telas com o Link",
      duration: "0:07:16",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Navegando entre telas com o history",
      duration: "0:09:50",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "AULA SOBRE ATUALIZAÇÃO - React Router Dom V6.",
      duration: "0:10:23",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Componentizando a nossa aplicação",
      duration: "0:09:23",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Componentizando o Botão",
      duration: "0:06:00",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Aprendendo sobre Props no React",
      duration: "0:13:31",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Alterando CSS com Props",
      duration: "0:14:15",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Desafio React",
      duration: "0:04:45",
      finished: false,
      module: "24",
      summary: "",
    },
    {
      title: "Grid template columns",
      duration: "0:11:18",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid template rows",
      duration: "0:01:46",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid gap",
      duration: "0:01:35",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid auto rows",
      duration: "0:04:16",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid column",
      duration: "0:03:17",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid row",
      duration: "0:02:06",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Display Grid na prática",
      duration: "0:07:14",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Grid area",
      duration: "0:05:53",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Propriedades para Alinhamento no container",
      duration: "0:05:38",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Propriedades para Alinhamento nos itens",
      duration: "0:02:23",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Origamid",
      duration: "0:01:21",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Desafio",
      duration: "0:01:55",
      finished: false,
      module: "25",
      summary: "",
    },
    {
      title: "Instalando o Yarn",
      duration: "0:01:03",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Iniciando o projeto do CodeBurger",
      duration: "0:13:40",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Instalando Nodemon e Sucrase",
      duration: "0:08:59",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Padronizando nosso código com Eslint + Prettier",
      duration: "0:15:12",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "MVC",
      duration: "0:04:47",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Conceitos sobre Docker",
      duration: "0:08:27",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Resolvendo problema de instalação do Docker no Windows",
      duration: "0:11:41",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Primeiro container Docker",
      duration: "0:08:44",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "SQL / Sequelize",
      duration: "0:07:46",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Instalando o Sequelize",
      duration: "0:11:48",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Primeira Migration",
      duration: "0:16:57",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Model de Usuário",
      duration: "0:09:38",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Configuração do Model de Usuário",
      duration: "0:11:41",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Controller de Usuário",
      duration: "0:15:46",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Validando dados com o Yup",
      duration: "0:18:42",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Validando email Duplicado",
      duration: "0:05:48",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Hash de senha",
      duration: "0:08:09",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Fazendo o login de usuário",
      duration: "0:17:52",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Migration de Produtos",
      duration: "0:06:03",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Controller de Produtos",
      duration: "0:08:31",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Upload de imagens com Multer",
      duration: "0:17:26",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Criando Model de Produtos",
      duration: "0:21:02",
      finished: false,
      module: "26",
      summary: "",
    },
    {
      title: "Conceitos de JWT",
      duration: "0:06:09",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Configurando token JWT pt. 1",
      duration: "0:08:01",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Configurando token JWT pt. 2",
      duration: "0:22:50",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Entendendo o relacionamento em Banco de Dados",
      duration: "0:06:55",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando tabela de categorias",
      duration: "0:14:59",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Validando categoria repetida",
      duration: "0:04:31",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando e excluindo campos de uma tabela",
      duration: "0:13:36",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando relacionamento entre tabelas",
      duration: "0:10:33",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Alterando Controller de produtos",
      duration: "0:06:22",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "MongoDB - Bancos SQL x Bancos NoSQL",
      duration: "0:11:23",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando conexão com o MongoDB",
      duration: "0:08:25",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando Scheme de pedidos",
      duration: "0:09:20",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Criando Controller de pedidos",
      duration: "0:25:36",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Gravando pedidos no MongoDB",
      duration: "0:04:11",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Atualizando status do pedido",
      duration: "0:09:31",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Validando usuário Admin",
      duration: "0:10:37",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Update do Produto",
      duration: "0:18:09",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Update de Categorias",
      duration: "0:16:58",
      finished: false,
      module: "27",
      summary: "",
    },
    {
      title: "Intro - CodeBurger - React",
      duration: "0:06:36",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Eslint + Prettier no React",
      duration: "0:15:12",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Estilos Globais com Styled Components",
      duration: "0:03:56",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Estilizando a tela de Login",
      duration: "0:22:42",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Formulário com React Hook Form",
      duration: "0:10:11",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Validando o formulário de Login",
      duration: "0:12:09",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Conectando Front end e Back end",
      duration: "0:11:19",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando componente de Button | PropTypes",
      duration: "0:14:06",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando tela de Register",
      duration: "0:14:04",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Toast Messages com React Toastify",
      duration: "0:20:07",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "React Hook - useContext",
      duration: "0:18:21",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Adicionando informações do usuário no useContext",
      duration: "0:07:24",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Gravando informações do usuário no Local Storage",
      duration: "0:12:28",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "ATUALIZAÇÃO - React Router Dom v6",
      duration: "0:00:30",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando as rotas da aplicação",
      duration: "0:08:11",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando rotas privadas",
      duration: "0:11:08",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Iniciando tela de Home",
      duration: "0:15:02",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Adicionando Token JWT as chamadas a API",
      duration: "0:10:11",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando Carrossel de categorias",
      duration: "0:21:24",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando Carrossel de ofertas",
      duration: "0:09:23",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Formatando valores monetários",
      duration: "0:06:52",
      finished: false,
      module: "28",
      summary: "",
    },
    {
      title: "Criando o Menu de seleção de categorias",
      duration: "0:16:38",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando Cards de Produtos",
      duration: "0:24:56",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando filtro por categorias",
      duration: "0:06:37",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Alterando exportação e importação de componentes e páginas",
      duration: "0:07:41",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Alterando importação dos Hooks",
      duration: "0:07:12",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando a lógica do carrinho",
      duration: "0:22:00",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando estrutura do carrinho",
      duration: "0:15:51",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Estilizando o carrinho",
      duration: "0:10:25",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Estilizando botões de quantidade",
      duration: "0:04:20",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Adicionando e deletando itens do carrinho",
      duration: "0:15:11",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Atualizando local storage",
      duration: "0:02:34",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando resumo do carrinho",
      duration: "0:19:41",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Criando lógica do resumo do carrinho",
      duration: "0:08:29",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Enviando pedido para a API",
      duration: "0:05:40",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Iniciando o Header da aplicação",
      duration: "0:16:01",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Finalizando o Header",
      duration: "0:10:54",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Deslogando o usuário",
      duration: "0:03:48",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Corrigindo links em categorias e produtos",
      duration: "0:13:49",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Adicionando nome do usuário ao Header",
      duration: "0:01:48",
      finished: false,
      module: "29",
      summary: "",
    },
    {
      title: "Validando se o usuário é Admin",
      duration: "0:13:57",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Instando o MUI na nossa aplicação",
      duration: "0:09:05",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Começando a construir nossa tabela com MUI",
      duration: "0:17:40",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Continuando a criação da nossa tabela com MUI",
      duration: "0:13:56",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Arrumando nossa tabela",
      duration: "0:09:25",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Atualizando status do pedido",
      duration: "0:23:22",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando menu de seleção de status",
      duration: "0:19:02",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Finalizando lógica do menu e select de status",
      duration: "0:14:51",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando menu lateral",
      duration: "0:19:37",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando logout Admin",
      duration: "0:06:25",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Iniciando tela de listagem de produtos",
      duration: "0:11:11",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Continuando a tela de listagem de produtos",
      duration: "0:15:51",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Organizando menu e tela de Admin",
      duration: "0:13:40",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Organizando link ativo no menu Admin",
      duration: "0:04:13",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Começando tela de adição de novo produto",
      duration: "0:05:57",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando formulário de adição de produto",
      duration: "0:07:34",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Estilizando formulário de novo produto",
      duration: "0:08:02",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando input de upload de imagem",
      duration: "0:12:06",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando select de categorias",
      duration: "0:18:59",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Validando formulário de criação do produto",
      duration: "0:20:11",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Corrigindo CSS do formulário de criação do usuário",
      duration: "0:02:34",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Enviando novo produto para o Back-end",
      duration: "0:10:22",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Criando tela de editar produtos",
      duration: "0:09:23",
      finished: false,
      module: "30",
      summary: "",
    },
    {
      title: "Finalizando tela de edição de usuários",
      duration: "0:10:16",
      finished: false,
      module: "30",
      summary: "",
    },
  ],
  modules: [
    {
      name: "Módulo Boas Vindas",
      link: "",
      type: "1",
    },
    {
      name: "Módulo Comunidade",
      link: "",
      type: "2",
    },
    {
      name: "Módulo Material de Apoio",
      link: "",
      type: "3",
    },
    {
      name: "Módulo Preparando o Ambiente",
      link: "",
      type: "4",
    },
    {
      name: "Módulo HTML",
      link: "",
      type: "5",
    },
    {
      name: "CSS pt. 1",
      link: "",
      type: "6",
    },
    {
      name: "CSS pt. 2",
      link: "",
      type: "7",
    },
    {
      name: "Git & Github",
      link: "",
      type: "8",
    },
    {
      name: "JavaScript pt.1",
      link: "",
      type: "9",
    },
    {
      name: "JavaScript pt.2 - Web",
      link: "",
      type: "10",
    },
    {
      name: "JavaScript pt.2",
      link: "",
      type: "11",
    },
    {
      name: "JavaScript pt.3",
      link: "",
      type: "12",
    },
    {
      name: "JavaScript pt.4",
      link: "",
      type: "13",
    },
    {
      name: "Carreira Profissional",
      link: "",
      type: "14",
    },
    {
      name: "Linkedin",
      link: "",
      type: "15",
    },
    {
      name: "Currículo",
      link: "",
      type: "16",
    },
    {
      name: "Entrevistas",
      link: "",
      type: "17",
    },
    {
      name: "Carreira Profissional",
      link: "",
      type: "18",
    },
    {
      name: "Freelancer",
      link: "",
      type: "19",
    },
    {
      name: "Iniciando no NODEJS",
      link: "",
      type: "20",
    },
    {
      name: "JavaScript Avançado",
      link: "",
      type: "21",
    },
    {
      name: "CSS Avançado - Display Flex",
      link: "",
      type: "22",
    },
    {
      name: "Iniciando no React",
      link: "",
      type: "23",
    },
    {
      name: "Continuando aplicação com React",
      link: "",
      type: "24",
    },
    {
      name: "CSS Avançado - Display GRID",
      link: "",
      type: "25",
    },
    {
      name: "Iniciando API do CodeBurger - Back End",
      link: "",
      type: "26",
    },
    {
      name: "Continuando a API do CodeBurger - Back End",
      link: "",
      type: "27",
    },
    {
      name: "CodeBurger - Front End pt. 1",
      link: "",
      type: "28",
    },
    {
      name: "CodeBurger - Front End pt. 2",
      link: "",
      type: "29",
    },
    {
      name: "CodeBurger - Front End pt. 3",
      link: "",
      type: "30",
    },
  ],
};
