const apiData = {
  lessons: [
    {
      title: "Seja Bem-vindo(a)",
      duration: "0:08:13",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Plataforma e Aulas",
      duration: "0:07:04",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "A Comunidade",
      duration: "0:15:38",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Juntos vamos mais rápido e mais longe",
      duration: "0:09:14",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Encontre seu Partner",
      duration: "0:04:08",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Aprendendo a Aprender pt. 1",
      duration: "0:08:54",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Aprendendo a Aprender pt. 2",
      duration: "0:09:52",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Você merece um troféu",
      duration: "0:05:25",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "O segredo para o Sucesso",
      duration: "0:05:05",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Como atingir o Sucesso",
      duration: "0:10:20",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Não cometa esses Erros",
      duration: "0:12:25",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Quadro de Metas",
      duration: "0:12:20",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Cronograma de Estudos",
      duration: "0:05:30",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "Conclusão",
      duration: "0:03:30",
      finished: false,
      module: "1",
      summary: "",
    },
    {
      title: "App DevClub",
      duration: "0:02:46",
      finished: false,
      category: "1",
      summary: "",
    },
    {
      title: "",
      duration: "",
      finished: false,
      category: "2",
      summary: "",
    },
  ],
  modules: [
    {
      name: "Módulo boas vindas",
      link: "https://aulas.devclub.com.br/aulas/devclub-full-stack-pro-intro",
      type: "1",
    },
    {
      name: "",
      link: "",
      type: "2",
    },
  ],
};
